##################################################
#makefile of pmtestx.asm (x=[1,2,3...])
##################################################
#input these command to command line by order ; then execute the following command------  B:\pmtest2.com  in the viture machine bochs Dos FreeDos
	sudo mount -o loop pm.img /mnt/floppy/
	sudo cp pmtest2.com /mnt/floppy/ -v
	sudo umount /mnt/floppy/

# B:pmtest2.com
